version: '3.8'

services:
  web:
    build: .
    container_name: flask_wallet
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    restart: always

  db:
    image: postgres:15
    container_name: postgres_wallet
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_wallet
    restart: always
    ports:
      - "6379:6379"

volumes:
  pg_data:
